"""add_stock_management_models

Revision ID: a2e6a70fcc01
Revises: 7c1d2e9a4b10
Create Date: 2026-09-28 15:58:49.142489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e6a70fcc01'
down_revision: Union[str, Sequence[str], None] = '7c1d2e9a4b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('detected_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_logs_camera_id'), 'camera_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_camera_logs_captured_at'), 'camera_logs', ['captured_at'], unique=False)
    op.create_table('financial_statements',
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('statement', sa.String(length=10), nullable=False),
    sa.Column('line_item', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'period_end', 'statement', 'line_item')
    )
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_forecast_date'), 'forecast_results', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecast_results_product'), 'forecast_results', ['product'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('records_written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_dataset'), 'ingestion_runs', ['dataset'], unique=False)
    op.create_table('market_prices',
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'trade_date')
    )
    op.create_table('shrimp_stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='kg', nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shrimp_stocks_product'), 'shrimp_stocks', ['product'], unique=False)
    op.create_index(op.f('ix_shrimp_stocks_recorded_at'), 'shrimp_stocks', ['recorded_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_shrimp_stocks_recorded_at'), table_name='shrimp_stocks')
    op.drop_index(op.f('ix_shrimp_stocks_product'), table_name='shrimp_stocks')
    op.drop_table('shrimp_stocks')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_ingestion_runs_dataset'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_forecast_results_product'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_date'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_camera_logs_captured_at'), table_name='camera_logs')
    op.drop_index(op.f('ix_camera_logs_camera_id'), table_name='camera_logs')
    op.drop_table('camera_logs')
    # ### end Alembic commands ###
